name: react app to docker

on:
  push:
    branches: ["main"]

jobs:
  build:
    # 운영체제 설치
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: docker build    # docker desktop 깐 느림
        uses: docker/setup-buildx-action@v3
      
      - name: docker login    # hub에 로그인
        uses: docker/login-action@v3    # 버전 확인 잘 하기
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # docker 사용자명
          password: ${{ secrets.DOCKERHUB_TOKEN }}
